### ISSUE TITLE
Its crashing on Vivo v1 device 

### ISSUE THREAD

**Issue by NileshJarad** [stephentuso/welcome-android#30] opened 2017-01-10 03:21 UTC
> 
>  android.view.InflateException: Binary XML file line #44: Error inflating class Button
>                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2338)
>                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
>                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:151)
>                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
>                                                                      at android.os.Handler.dispatchMessage(Handler.java:110)
>                                                                      at android.os.Looper.loop(Looper.java:193)
>                                                                      at android.app.ActivityThread.main(ActivityThread.java:5292)
>                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
>                                                                      at java.lang.reflect.Method.invoke(Method.java:515)
>                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
>                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
>                                                                      at dalvik.system.NativeStart.main(Native Method)
>                                                                   Caused by: android.view.InflateException: Binary XML file line #44: Error inflating class Button
>                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
>                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
>                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
>                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
>                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
>                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
>                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
>                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
>                                                                      at android.support.v7.app.AppCompatDelegateImplV9.b(AppCompatDelegateImplV9.java:284)
>                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
>                                                                      at com.stephentuso.welcome.ui.WelcomeActivity.onCreate(WelcomeActivity.java:42)
>                                                                      at android.app.Activity.performCreate(Activity.java:5264)
>                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
>                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
>                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
>                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:151) 
>                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
>                                                                      at android.os.Handler.dispatchMessage(Handler.java:110) 
>                                                                      at android.os.Looper.loop(Looper.java:193) 
>                                                                      at android.app.ActivityThread.main(ActivityThread.java:5292) 
>                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                      at java.lang.reflect.Method.invoke(Method.java:515) 
>                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
>                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
>                                                                      at dalvik.system.NativeStart.main(Native Method) 
>                                                                   Caused by: android.content.res.Resources$NotFoundException: Resource is not a Drawable (color or path): TypedValue{t=0x1/d=0x7f02005f a=3 r=0x7f02005f}
>                                                                      at android.content.res.Resources.loadDrawable(Resources.java:2124)
>                                                                      at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
>                                                                      at android.view.View.<init>(View.java:3579)
>                                                                      at android.widget.TextView.<init>(TextView.java:642)
>                                                                      at android.widget.Button.<init>(Button.java:107)
>                                                                      at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:61)
>                                                                      at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:57)
>                                                                      at android.support.v7.app.AppCompatViewInflater.a(AppCompatViewInflater.java:109)
>                                                                      at android.support.v7.app.AppCompatDelegateImplV9.b(AppCompatDelegateImplV9.java:1013)
>                                                                      at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1072)
>                                                                      at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
>                                                                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
>                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
>                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
>                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
>                                                                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
>                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
>                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
>                                                                      at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
>                                                                      at android.support.v7.app.AppCompatDelegateImplV9.b(AppCompatDelegateImplV9.java:284) 
>                                                                      at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
>                                                                      at com.stephentuso.welcome.ui.WelcomeActivity.onCreate(WelcomeActivity.java:42) 
>                                                                      at android.app.Activity.performCreate(Activity.java:5264) 
>                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088) 
>                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
>                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390) 
>                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:151) 
>                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
>                                                                      at android.os.Handler.dispatchMessage(Handler.java:110) 
>                                                                      at android.os.Looper.loop(Looper.java:193) 
>                                                                      at android.app.ActivityThread.main(ActivityThread.java:5292) 
>                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
>                                                                      at java.lang.reflect.Method.invoke(Method.java:515) 
>                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
>                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
>                                                                      at dalvik.system.NativeStart.main(Native Method) 
>

**Comment by stephentuso** [comment] 2017-01-10 05:04
I'll take a closer look tomorrow, looks like a style issue. Just to be sure, have you set the theme in the android manifest as shown [here](https://github.com/stephentuso/welcome-android#extend-welcomeactivity)? And if so, are you using a customized theme or one of the defaults?

**Comment by NileshJarad** [comment] 2017-01-10 13:40
I have used default theme as you mentioned in **README.md**

**Comment by stephentuso** [comment] 2017-01-16 20:57
Could you download the [sample](https://play.google.com/store/apps/details?id=com.stephentuso.welcomeexample) and see if it works? I can't reproduce the crash, I think there might be an issue with the styles in your app, this will tell me for sure though.

**Comment by stephentuso** [comment] 2017-03-23 18:15
Closing this since it's been 2 months, let me know if this is still an issue, thanks

**Closed by stephentuso** 2017-03-23 18:15 UTC
