### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ndung** [stephentuso/welcome-android#51] opened 2017-09-28 18:22 UTC
Caused by: android.view.InflateException: Binary XML file line #30: Binary XML file line #30: You must supply a layout_height attribute.
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                         at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                                         at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                         at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                         at com.stephentuso.welcome.WelcomeActivity.onCreate(WelcomeActivity.java:33)

**Comment by stephentuso** [comment] 2017-09-28 18:25
Duplicate of #29 

https://github.com/stephentuso/welcome-android#extend-welcomeactivity

**Closed** 2017-09-28 18:27 UTC
Labels: duplicate
